import {
  generateLocalInfraComposeOptionsSchema,
  localInfraServiceImageByName,
  localInfraServiceNameSchema,
  localStorageBucketInitImage,
  localStorageBucketInitServiceName,
  type GenerateLocalInfraCompose,
  type HearthkitProjectName,
  type LocalInfraServiceName,
} from './cli-contract.ts'
import { deriveLocalStorageBucketName } from './derive-local-storage-bucket-name.ts'

/** Credentials baked into the generated Postgres and MinIO services; they match defaultLocalAdminDatabaseUrl. */
const localInfraCredential = 'hearthkit'

/** The address the bucket init container reaches MinIO on: inside the compose network, so it never depends on a published host port. */
const localStorageServiceEndpoint = 'http://minio:9000'

/** Services whose data survives a compose down, each with one named volume derived from the project name. */
const volumeBackedServiceNames = [
  'postgres',
  'minio',
] as const satisfies readonly LocalInfraServiceName[]

/**
 * Builds the local infra compose file. Pure and deterministic: the same options always produce the
 * same bytes, services are emitted in a fixed order whatever order the caller listed them in, and
 * every image comes from localInfraServiceImageByName so there is one place to bump a version. The
 * bucket init container follows minio whenever minio is emitted, and only then.
 */
export const generateLocalInfraCompose: GenerateLocalInfraCompose = (options) => {
  const { hearthkitProjectName, infraServices } =
    generateLocalInfraComposeOptionsSchema.parse(options)
  const requestedServiceNames = new Set(infraServices)
  const emittedServiceNames = localInfraServiceNameSchema.options.filter((serviceName) =>
    requestedServiceNames.has(serviceName),
  )

  const serviceBlocks = emittedServiceNames.map((serviceName) =>
    serviceName === 'minio'
      ? [
          ...buildServiceBlock(serviceName, hearthkitProjectName),
          ...buildBucketInitBlock(hearthkitProjectName),
        ]
      : buildServiceBlock(serviceName, hearthkitProjectName),
  )
  const volumeNames = volumeBackedServiceNames
    .filter((serviceName) => requestedServiceNames.has(serviceName))
    .map((serviceName) => namedVolumeFor(hearthkitProjectName, serviceName))

  const lines = [
    '# Generated by hearthkit. This file is yours: hearthkit never overwrites an existing docker-compose.yml.',
    `name: ${hearthkitProjectName}`,
    '',
    'services:',
    ...serviceBlocks.flat(),
  ]

  if (volumeNames.length > 0) {
    lines.push('', 'volumes:', ...volumeNames.map((volumeName) => `  ${volumeName}:`))
  }

  return `${lines.join('\n')}\n`
}

/** The named volume a service keeps its data in; prefixed with the project so two projects never share one. */
function namedVolumeFor(
  hearthkitProjectName: HearthkitProjectName,
  serviceName: LocalInfraServiceName,
): string {
  return `${hearthkitProjectName}-${serviceName}-data`
}

/** The compose lines for one service, indented ready to sit under the services key. */
function buildServiceBlock(
  serviceName: LocalInfraServiceName,
  hearthkitProjectName: HearthkitProjectName,
): string[] {
  const header = [
    `  ${serviceName}:`,
    `    image: '${localInfraServiceImageByName[serviceName]}'`,
    `    container_name: ${hearthkitProjectName}-${serviceName}`,
    '    restart: unless-stopped',
  ]

  if (serviceName === 'postgres') {
    return [
      ...header,
      '    environment:',
      `      POSTGRES_USER: ${localInfraCredential}`,
      `      POSTGRES_PASSWORD: ${localInfraCredential}`,
      `      POSTGRES_DB: ${localInfraCredential}`,
      '    ports:',
      "      - '5432:5432'",
      '    volumes:',
      `      - ${namedVolumeFor(hearthkitProjectName, serviceName)}:/var/lib/postgresql/data`,
      '    healthcheck:',
      `      test: ['CMD-SHELL', 'pg_isready -U ${localInfraCredential} -d ${localInfraCredential}']`,
      '      interval: 5s',
      '      timeout: 5s',
      '      retries: 20',
    ]
  }

  if (serviceName === 'minio') {
    return [
      ...header,
      "    command: ['server', '/data', '--console-address', ':9001']",
      '    environment:',
      `      MINIO_ROOT_USER: ${localInfraCredential}`,
      `      MINIO_ROOT_PASSWORD: ${localInfraCredential}`,
      '    ports:',
      "      - '9000:9000'",
      "      - '9001:9001'",
      '    volumes:',
      `      - ${namedVolumeFor(hearthkitProjectName, serviceName)}:/data`,
      '    healthcheck:',
      "      test: ['CMD', 'mc', 'ready', 'local']",
      '      interval: 5s',
      '      timeout: 5s',
      '      retries: 20',
    ]
  }

  return [...header, '    ports:', "      - '1025:1025'", "      - '8025:8025'"]
}

/**
 * The compose lines for the container that creates the local storage bucket. It carries no restart,
 * ports, volumes or environment keys on purpose: it publishes and stores nothing, and compose's
 * default restart policy of no is the right one for a container whose work is already done.
 */
function buildBucketInitBlock(hearthkitProjectName: HearthkitProjectName): string[] {
  const localStorageBucketName = deriveLocalStorageBucketName(hearthkitProjectName)
  const bucketInitCommand = [
    `mc alias set local ${localStorageServiceEndpoint} ${localInfraCredential} ${localInfraCredential}`,
    `mc mb --ignore-existing local/${localStorageBucketName}`,
    'tail -f /dev/null',
  ].join(' && ')

  return [
    '  # Creates the bucket, then idles on purpose. It is not stuck. hearthkit dev infra up always',
    '  # runs docker compose up --wait. That command fails if a service has exited, whatever its',
    '  # exit code. Remove the tail -f /dev/null below and every dev infra up fails, even though',
    '  # the bucket is created. A failed step stops the && chain before tail and exits nonzero.',
    `  ${localStorageBucketInitServiceName}:`,
    `    image: '${localStorageBucketInitImage}'`,
    `    container_name: ${hearthkitProjectName}-${localStorageBucketInitServiceName}`,
    '    depends_on:',
    '      minio:',
    '        condition: service_healthy',
    `    entrypoint: ['sh', '-c', '${bucketInitCommand}']`,
  ]
}
